# Dependencies
markdown:         redcarpet
highlighter:      pygments


# Permalinks
permalink:        pretty

# Setup
title:            Hazzik's blog
tagline:          ''
description:      ''
url:              http://alexzaytsev.me
timezone:         'Pacific/Auckland'

author:
  name:           'Alexander Zaytsev'
  url:            http://alexzaytsev.me

paginate:         5

github:
  source:    'http://github.com/hazzik/alexzaytsev.me/edit/gh-pages/'

gems:
  - jekyll-redirect-from
