# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hazzik`s blog
tagline:          ''
description:      ''
url:              http://alexzaytsev.me

author:
  name:           'Alexander Zaytsev'
  url:            http://alexzaytsev.me

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/hazzik
